# Simulating Coin Flips

In [1]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
# outcome of one coin flip
# randint let's you produce random numbers between 0 and 1. 0 is the default minimum so no need to specify. 
# Note that 0 is inclusive but the 2 is exclusive so therefore it is between 0 and 1
np.random.randint(2)

1

In [3]:
# outcomes of ten thousand coin flips
# you can specify as many coin tosses as you want with the size parameter
# results are stored in an array
np.random.randint(2, size=10000)

array([1, 0, 1, ..., 0, 1, 0])

In [4]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5001

In [5]:
# outcome of one coin flip
# choice let's you specify a choice of numbers as the outcome
np.random.choice([0, 1])

0

In [6]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 1, 0, ..., 0, 1, 0])

In [7]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.5006

In [8]:
# outcomes of ten thousand biased coin flips
# the p let's you specify the probabilities of each number inthe array
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 1, 0, ..., 0, 0, 0])

In [9]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.1978

# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. 

Note that 0 = heads and 1 = tails.

For die rolls, the correct integers to match the numbers onthe sides of standard 6 sided die are used.

### 1. Two fair coin flips produce exactly two heads

In [18]:
# simulate 1 million tests of two fair coin flips
# Note that the size generates a two column array for 2 coins
tests = np.random.randint(2, size=(int(1e6), 2))
print(tests)

# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

[[0 0]
 [0 0]
 [1 0]
 ...
 [0 0]
 [0 0]
 [1 1]]
[0 0 1 ... 0 0 2]


0.250061

### 2. Three fair coin flips produce exactly one head

In [32]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))
print(tests)

# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

[[0 1 1]
 [0 1 1]
 [0 1 1]
 ...
 [1 1 0]
 [1 1 0]
 [0 1 0]]
[2 2 2 ... 2 2 1]


0.37402

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [34]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()

tests = np.random.choice([0, 1], size=(int(1e6), 3), p=([0.6,0.4]))
print(tests)

# sums of all tests
test_sums = tests.sum(axis=1) 
print(test_sums)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

[[0 1 0]
 [0 1 0]
 [0 1 1]
 ...
 [0 1 1]
 [0 1 0]
 [1 0 1]]
[1 1 2 ... 2 1 2]


0.288006

### 4. A die rolls an even number

In [44]:
# simulate 1 million tests of one die roll
tests = np.random.randint(1,7, size=(int(1e6)))
print(tests)
                          
# proportion of tests that produced an even number
(tests % 2 == 0).mean()

[3 6 1 ... 1 1 4]


0.499416

### 5. Two dice roll a double

In [49]:
# simulate the first million die rolls
first = np.random.randint(1,7,size=(int(1e6)))
# or
first = np.random.choice(np.arange(6), size=int(1e6))


# simulate the second million die rolls
second = np.random.randint(1,7,size=(int(1e6)))
#or
second = np.random.choice(np.arange(6), size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.16708